spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  cache:
    cache-names: mdc-cache
  datasource:
    url: jdbc:mysql://fwd-db-mysql:3306/fwd_mdc?characterEncoding=utf8&useSSL=false

liquibase:
  change-log: classpath:liquibase/index.xml
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  url: ${spring.datasource.url}

mybatis:
  type-aliases-package: com.fwd.provider.model.domain
  mapper-locations: classpath:mapper/*.xml,classpath*:sdk/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.fwd.common.base.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    client:
      clientId: fwd-client-mdc
      clientSecret: fwdClientSecret
      access-token-uri: http://fwd-gateway:7979/uac/oauth/token
      user-authorization-uri: http://fwd-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://fwd-gateway:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://fwd-provider-uac:8000/oauth/token_key

fwd:
  enableSqlLogInterceptor: false
  dingTalk:
    webhookToken:
      sendException: 7b0fcc73f3d2be1415c5d31e5b34100c689961454af15a61635749ba0d8*****
      jobListener: 7b0fcc73f3d2be1415c5d31e5b34100c689961454af15a61635749ba0d8*****
  token:
    interceptor:
      enable: true
  zk:
    zkAddressList: fwd-provider-zk:2181
  aliyun:
    rocketMq:
      enable: false
      reliableMessageConsumer: false
      reliableMessageProducer: true
      namesrvAddr: fwd-mq-rocket:9876
      instanceName: fwd-provider-mdc
      consumerGroup: CID_MDC
      producerGroup: PID_MDC
  oauth2:
    jwtSigningKey: fwd
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt
